name: Achievement guide update

on:
  pull_request_target:
    paths:
      - 'guides/**'
      - '.utils/achievements.go'
      - 'games.yml'
      - 'main.go'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref }}
          submodules: recursive
    
      - name: Configure Cmake
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          source-dir: LlamaGPTJ-chat/

      - name: Run Script
        run: go run main.go achievements

      - name: Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: achievement guide update by github actions [bot]"
