name: Achievement guide update

on:
  pull_request:
    paths:
      - 'guides/**'
      - '.utils/achievements.go'
      - 'games.yml'
      - 'main.go'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@master
        with:
          configFile: .github/commitlint.config.js

      - name: Run Script
        run: go run main.go achievements

      - name: Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "multi: Achievement update by github actions [bot]"
