name: Achievement guide update

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
jobs:
  changed-files:
    name: Get changed files
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          submodules: recursive

      - name: Get changed games
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          dir_names: "true"
          dir_names_exclude_current_dir: "true"
          dir_names_max_depth: 1
          path: guides/
          matrix: true

  matrix-job:
    name: Stat update matrix
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: needs.changed-files.outputs.matrix != '[]'
    strategy:
      matrix:
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          submodules: recursive

      - name: Run script
        run: go run main.go "${{ matrix.files }}"

      - name: Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: "${{ matrix.files }}" update by github actions [bot]'

  stat_update:
    name: All stats update
    runs-on: ubuntu-latest
    needs: [changed-files]
    if: needs.changed-files.outputs.matrix == '[]'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          submodules: recursive

      - name: Run script
        run: go run main.go all

      - name: Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: all achievement stats update by github actions [bot]"
