name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@master
        with:
          configFile: .github/commitlint.config.js

      - name: Run Script
        run: go run build.go

      - name: Commit all changed files back to the repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ github.event.pull_request.title }} amendment
