name: Build

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Script
        run: go run build.go

      - name: Commit changes
        uses: EndBug/add-and-commit@main
        with:
          commit: '--amend'
          message: '${{ github.event.pull_request.title }}'
          tag_push: '--force'
