name: Commitlint

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Lint commit messages
      uses: wagoid/commitlint-github-action@master
      with:
        configFile: .github/commitlint.config.js
