name: "Markdown lint"

on:
  pull_request_target:
    paths:
      - "**.md"

jobs:
  main:
    name: Validate markdown
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
          submodules: recursive

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **.md
          separator: ","

      - name: Lint markdown
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          config: .markdownlint-cli2.jsonc
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
