name: Scheduled achievement guide update

on:
  schedule:
    - cron: '0 0 * * 6,0'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Run Script
        run: go run main.go achievements

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'docs: achievement guide update by github actions [bot]'
          title: 'docs: achievement guide update by github actions [bot]'
          base: main
          branch: fix/scheduled_guide_update
          delete-branch: true

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v2
        with:
          github-token: ${{ secrets.PAT }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          repo: lukojy3d/perfect100

      - name: Merge Pull Request
        if: ${{ steps.cpr.outputs.pull-request-number }}
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          method: squash
          number: ${{ steps.cpr.outputs.pull-request-number }}
          repo: lukojy3d/perfect100
